#!/bin/bash

echo "🔧 Fixing Appwrite Collection Attributes"
echo ""
echo "This script will guide you through fixing the attribute types in Appwrite Console"
echo ""
echo "============================================"
echo "MANUAL STEPS TO FIX IN APPWRITE CONSOLE:"
echo "============================================"
echo ""
echo "1. Go to: https://skillhub.avodahsystems.com/console"
echo "2. Navigate to: Databases → userData → Skills Collection → Attributes"
echo ""
echo "3. For each of these attributes: lat, long, averageRating"
echo "   - Click the ⋮ (three dots) menu"
echo "   - Select 'Delete'"
echo "   - Confirm deletion"
echo ""
echo "4. After deleting, create new attributes:"
echo ""
echo "   For 'lat':"
echo "   - Click 'Create Attribute'"
echo "   - Type: Float"
echo "   - Key: lat"
echo "   - Size: Leave default"
echo "   - Required: NO (uncheck)"
echo "   - Default: 0.0"
echo "   - Click 'Create'"
echo ""
echo "   For 'long':"
echo "   - Click 'Create Attribute'"
echo "   - Type: Float"
echo "   - Key: long"
echo "   - Size: Leave default"
echo "   - Required: NO (uncheck)"
echo "   - Default: 0.0"
echo "   - Click 'Create'"
echo ""
echo "   For 'averageRating':"
echo "   - Click 'Create Attribute'"
echo "   - Type: Float"
echo "   - Key: averageRating"
echo "   - Size: Leave default"
echo "   - Required: NO (uncheck)"
echo "   - Default: 0.0"
echo "   - Click 'Create'"
echo ""
echo "5. Wait 1-2 minutes for Appwrite to process the changes"
echo ""
echo "6. Restart your Flutter app with: flutter run -d emulator-5554"
echo ""
echo "============================================"
echo ""
echo "✨ After completing these steps, your skills should render correctly!"
