name: Deploy Skillhub to Google Play

on:
  push:
    branches:
      - main  # or whatever branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17.x'
          distribution: 'zulu'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'  # Specify the Flutter version you need
          channel: 'stable'
      - run: flutter pub get
      - run: flutter build appbundle --release  # This builds an App Bundle, which is recommended for Google Play
      
      # Steps for signing the app
      - name: Decode Android keystore
        env:
          ANDROID_KEYSTORE: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: echo $ANDROID_KEYSTORE | base64 --decode > android/upload-keystore.jks
      
      - name: Decode Android key properties
        env:
          ANDROID_KEY_PROPERTIES: ${{ secrets.ANDROID_KEY_PROPERTIES_BASE64 }}
        run: echo $ANDROID_KEY_PROPERTIES | base64 --decode > android/key.properties
      
      - name: Set up signing environment
        run: |
          echo "STORE_PASSWORD=${{ secrets.STORE_PASSWORD }}" >> $GITHUB_ENV
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> $GITHUB_ENV
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> $GITHUB_ENV
      
      - name: Deploy to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAYSTORE_SERVICE_ACCOUNT }}
          packageName: com.avodah.skillhub.skillhub
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal  # or 'alpha', 'beta', 'production'
          status: completed